version: 2
jobs:
  build:

    macos:
      xcode: "9.1.0"

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-carthage-{{ checksum "Cartfile.lock" }}

      - run:
          name: Bundler
          command: bundle install

      - run:
          name: Carthage
          command: 

      - run:
          name: Build and Test
          command: bundle exec fastlane scan
          environment:
            LC_CTYPE: "en_US.UTF-8"
            LANG: "en_US.UTF-8"


      # Collect XML test results data to show in the UI,
      # and save the same XML files under test-results folder
      # in the Artifacts tab
      - store_test_results:
          path: test_output/report.xml
      - store_artifacts:
          path: /tmp/test-results
          destination: scan-test-results
      - store_artifacts:
          path: ~/Library/Logs/scan
          destination: scan-logs

      - save_cache:
          key: v1-carthage-{{ checksum "Cartfile.lock" }}
          paths:
            - Carthage
