version: 2
jobs:
  
  test:

    macos:
      xcode: "9.1.0"
    shell: /bin/bash --login -eo pipefail
      
    steps:
      - checkout

      - restore_cache:
          keys:
          - v2-carthage-{{ checksum "Cartfile.resolved" }}

      - run:
          name: Bundler
          command: bundle install

      - run:
          name: Carthage
          command: sh Scripts/buildDeps.sh

      - run:
          name: Build and Test
          command: bundle exec fastlane test
          environment:
            LC_CTYPE: "en_US.UTF-8"
            LANG: "en_US.UTF-8"


      # Collect XML test results data to show in the UI,
      # and save the same XML files under test-results folder
      # in the Artifacts tab
      - store_test_results:
          path: test_output/report.xml
      - store_artifacts:
          path: /tmp/test-results
          destination: scan-test-results
      - store_artifacts:
          path: ~/Library/Logs/scan
          destination: scan-logs

      - save_cache:
          key: v2-carthage-{{ checksum "Cartfile.resolved" }}
          paths:
            - Carthage

  deploy:

    macos:
      xcode: "9.1.0"
    shell: /bin/bash --login -eo pipefail
      
    steps:
      - checkout

      - restore_cache:
          keys:
          - v2-carthage-{{ checksum "Cartfile.resolved" }}

      - run:
          name: Bundler
          command: bundle install

      - run:
          name: Carthage
          command: sh Scripts/buildDeps.sh

      - run:
          name: Build and Deploy
          command: bundle exec fastlane beta
          environment:
            LC_CTYPE: "en_US.UTF-8"
            LANG: "en_US.UTF-8"

workflows:
  version: 2
  test_beta:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: beta
